syntax = "proto3";

package sf.authentication.v1;

option go_package = "github.com/streamingfast/dauth/sf/authentication/v1;pbauth";

service Authentication {
  rpc Authenticate(AuthRequest) returns (AuthResponse);
}

message AuthRequest {
  string url = 1;
  repeated Header headers = 2;
  string ip = 3;
  // The number of times we called Authenticate for a given long running connection (i.e. continuous auth)
  uint64 auth_count = 4;
}

message Header {
  string key = 1;
  string value = 2;
}

message AuthResponse {
  repeated Header authenticated_headers = 3;
  // Key-value pairs indicating service cut-off reasons, the key will always be
  // one of:
  // - "substreams"
  // - "token_api"
  //
  // And the values will be human-readable explanations for the cut-off in English.
  // If a service is in the map, it means the service is cut-off and caller should
  // act accordingly.
  //
  // Otherwise, if a service is assumed to be allowed.
  map<string, string> service_cut_off = 4;
}